remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: [Another Translate Toolkit]
description: [Management RC/PO/POT/XLIFF languages files]
show_downloads: "true"
github:
  zip_url: https://github.com/ClaudiaCoord/Another-RC-PO-POT-XLIFF-Translate-Toolkit/releases/download/1.0.0/AnotherTranslateToolkitx64.msi
  tar_url: https://github.com/ClaudiaCoord/Another-RC-PO-POT-XLIFF-Translate-Toolkit/releases/download/1.0.0/AnotherTranslateToolkitx86.msi
